export type { ContractContext as ERC20Interface } from './ERC20'
export type { ContractContext as ERC721Interface } from './ERC721'
export type { ContractContext as MasterChefInterface } from './MasterChef'
export type { ContractContext as MulticallInterface } from './Multicall'
export type { ContractContext as PancakeRouterInterface } from './PancakeRouter'
export type { ContractContext as ReferenceBulkInterface } from './ReferenceBulk'
